- package.json
- src/cep-promise.js
Don't use the full lodash module. When you do that you load the full module (almost 2MB) in memory and than import just the part you want.
When this happen you have a lot of bytes unused in memory.
With this change, the only thing in memory is the part that you use and its dependences.
> Replace lodash for lodash.get

- src/cep-promise.js
- test/e2e/cep-promise.spec.js
- test/unit/cep-promise.spec.js
Esse PR normaliza o output de erros para ser sempre uma array de objetos.
Razões: https://github.com/filipedeschamps/cep-promise/issues/37#issuecomment-252024584
> Normalizar erros para sempre ser uma array de objetos

- README.md
- package.json
- src/cep-promise.js
- src/errors/cep-promise.js
- src/errors/service.js
- src/services/correios.js
- src/services/viacep.js
- test/e2e/cep-promise.spec.js
- test/unit/cep-promise.spec.js
Proposta para alterar a interface de erro da biblioteca para a versão `2.0`
Em resumo foram criados dois Custom Errors:
1. `ServiceError`: que deve ser lançado pelos fornecedores de CEP
2. `CepPromiseError`: que deve ser lançado pela biblioteca
E no final das contas, o usuário vai ter que lidar com duas variações de erro (pelo campo `type`):
1. `validation_error`: quando o formato está errado
2. `service_error`: quando o formato está certo, mas o CEP não existe ou os serviços estão offline.
O formato do erro está mais flexível e pode ser expandindo sem causar uma breaking change:
```
{
message: 'Todos os serviços de CEP retornaram erro.',
type: 'service_error',
errors: [{
message: 'CEP NAO ENCONTRADO',
service: 'correios'
}, {
message: 'CEP não encontrado na base do ViaCEP.',
service: …
```
> feat(error): change public error interface to use Custom Error

- package.json
Desta forma fazemos o build diretamente do `src` e usando os transformers do jeito certo.
Arquivo não gziped por hora está `363K`.
> Conserta o suporte ao browser

- package.json
- src/services/correios-browser-mock.js
Isso reduz o build do browser de `236K` para `16K` (sem gzip). Como o Correios não aceita CORS, não vale a pena incluir ele.
E como agora temos uma propagação legal de erros, basta rejeitar o serviço mock com um ServiceError 👍
> feat(browser): use a mock Correios service only on browser build

- README.md
The attribute "zipcode" was not being sent from the application, it is "cep" instead.
> chore(readme): Adjusting returning object example

- index.d.ts
Com essa definition o pacote poderá ser importado em um projeto TypeScript com `import { default as  cep }  from 'cep-promise'`.
> Definition para TypeScript

- src/cep-promise.js
Refactor `throwApplicationError` function for using destructuring assignment.
> Destructing throw application error func

- bower.json
Esse PR tem como objetivo eliminar o _warning_ abaixo que foi pego ao executar `bower install cep-promise`.
> Atualiza a versão da lib no Bower para a mesma do NPM

- README.md
O badge de build não adiciona muita informação, a master nunca vai estar quebrada ou ao menos não vai ser um badge que vai ter alguma influencia nisso.
Pessoas saberem quantos downloads por mês está sendo feito do módulo expõe uma credibilidade muito interessante.
O que acham?
> chore(readme): replace Build with Downloads/month badge

- README.md
Adicionando instalação via CDN para simplificar a entrada de novos usuários.
(Só pra manter no mínimo um PR ativo hahaha)
> Adicionando instalação usando jsDelivr como CDN

- .travis.yml
- README.md
Ja que a build "node" no travis roda com a versão mais nova (9.x) achei que seria justo falar que damos suporte a ela e adicionei o `8` no travis ja que não é mais latest.
> Atualiza o travis e o readme com versões atuais do node

- README.md
corrigido o exemplo de typescript pra angular 2
> fix: typescript example in readme

- .npmignore
- package.json
Ignorar arquivos não necessários para o uso do módulo. Hoje apesar de ser usado um npmignore [vários arquivos](https://unpkg.com/cep-promise@3.0.0/) que não precisam estar no npm estão sendo mandados para lá. Uma abordagem seria adicionar ele no npmignore, no entanto é mais fácil dizer o que deve ir para o npm em vez do que não deve ir. Ai entra a [propriedade `files` do `package.json`](https://docs.npmjs.com/files/package.json#files) nela você adiciona o que não deve ser ignorado, todo o resto é ignorado por padrão, facilitando a configuração e futuras mudanças.
> build(ignore): add files property to package.json

- package.json
Closes https://github.com/filipedeschamps/cep-promise/issues/124
Em resumo, o `isomorphic-unfetch` tava declarado com `^` e pegando automaticamente o último release do móduo `2.1.1` e por algum motivo começou a gerar uma incompatibilidade com versões do Node.js abaixo de 7.
Fixando a versão do módulo para `2.0.0` volta a passar a `master`. Mais para frente precisamos entender o que foi esse bump de versão, porque eu não consigo encontrar as releases notes.
> fix(dependency): lock `isomorphic-unfetch` to version `2.0.0`

- README.md
O pacote já está na base do Yarn em https://yarn.pm/cep-promise. Só adicionei o comando ao README.md.
> Adicionado comando para instalação via Yarn

- package-lock.json
Esse PR é o resultado de rodar no terminal o comando `npm audit fix` em que ele busca todas as dependências por brechas de segurança. Todas as dependências de produção estão atualizadas, porém para dependências de desenvolvimento (`devDependencies`) temos vários pacotes que não. Independente disso, o `npm audit fix` vai diretamente no `package-lock.json` para fazer bump das versões que encontrar.
Em seguida seria legal fazer o bump manual das `devDependencies` 👍
> dev-dependencies: update for be compliant with npm audit fix

- index.d.ts
A ideia é ser usada no import, junto com com o typescript, no modelo 
import { CEP } from 'cep-promise'
> Adicionada a exportação da interface  CEP

- package.json
- src/services/viacep.js
Ao tentar alterar o user-agent, o browser acusa o erro: Refused to set unsafe header "user-agent"
> Set user-agent error on Browser

- index.d.ts
export estava com problemas em projetos com compilação typescript, exportando por default corrige esse problema.
> [TS] Altera declaração de exportação para melhorar utilização pela compilação em typescript

- index.d.ts
Corrige importações do cep-promise utilizando typescript (https://github.com/BrasilAPI/cep-promise/issues/212).
- O workarround do namespace não é mais necessário, devendo ser utilizada a opção de esModuleInterop:
```json
{
"compilerOptions": {
"esModuleInterop": true
}
}
```
- O export nomeado estava incorreto, pois não é possível fazer ```import {  cep } from 'cep-promise'```.
- Torna parâmetro `configurations` opcional.
> Correções typescript

- src/services/widenet.js
- test/unit/cep-promise-browser.spec.js
- test/unit/cep-promise-node.spec.js
- test/unit/cep-promise-providers.spec.js
Referencia o [PR#248](https://github.com/BrasilAPI/cep-promise/pull/248) para agilização do review.
> Estamos fechando o acesso público ao ws.apicep.com e pra não deixar a comunidade sem acesso, criamos uma alternativa que oferece exatamente os mesmos dados, mas baseado em um CDN de arquivos estáticos em um S3, atualizados de forma assíncrona.
> 
> Nossa proposta pro webservice antigo era buscar os dados do CEP em tempo real caso ele esteja desatualizado ou não exista em nossa base, porém devido ao volume gigantesco de pesquisas de CEPs inválidos (tentativas de dump forçado, scraping, etc) nossa fila de atualizações ficava quase sempre prejudicada, mesmo com restrições de flood e etc.
> 
> O acesso público novo não tem limite de consulta e não tem restrição cors. Exemplo do novo endereço: …
> Alteração no endereço público da apicep.com

- index.d.ts
- test/e2e/cep-promise.spec.js
Com uma descrição objetiva e minimalista em cada tipo e propriedades declaradas, o código se torna totalmente intuitivo dentro do próprio editor uma vez que você pode ler o que cada opção é ou faz em tempo real enquanto cria seu próprio código 🧙🏻
---
Essa é uma alternativa para o PR #261, porém sem mudanças críticas (*breaking changes*) e unindo o melhor do que já existe com a solução proposta pelo @arturdonda.
Com esse **PR**, agora é possível utilizar a opção `providers` de ambas as formas:
```ts
import cep, { AvailableProviders } from 'cep-promise';
cep('05010000', {
providers: [AvailableProviders.correios],
});
cep('05010000', {
providers: ['correios', 'viacep'],
});
cep('05010000', {
providers: [AvailableProviders.correios, 'viacep'],
});
```
---
Não era minha intenção alterar nada …
> feat(index.d.ts): flexible `AvailableProviders` and minimal documentation
